application: scoretool
version: master
runtime: python
api_version: 1

default_expiration: '3650d'

handlers:
- url: /remote_api_hidden
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  secure: optional
  login: admin

- url: /stats.*
  script: $PYTHON_LIB/google/appengine/ext/appstats/ui.py

- url: /media
  static_dir: _generated_media
  secure: optional

- url: /static
  static_dir: static

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico

- url: /.*
  script: common/appenginepatch/main.py
  secure: optional
