#!/usr/bin/env python

INDEXES = """
django_admin_log:content_type,object_id,action_time
django_admin_log:user,-action_time
__Stat_Kind__:kind_name,-timestamp
prefixes_prefix:length,timestamp
prefixes_dotcomprefix:length,-count
prefixes_dotcomsuffix:length,-count
tests_comparison:path,-timestamp
dns_lookup:-__key__
dns_lookup:com,backwards
domains_domain:-__key__
domains_domain:length,-score
""".split()

for length in range(1, 7):
    INDEXES.append('domains_domain:left%d,length,-score' % length)
    INDEXES.append('domains_domain:right%d,length,-score' % length)


print 'indexes:'
for index in INDEXES:
    kind, properties = index.split(':')
    print
    print '- kind:', kind
    print '  properties:'
    for property in properties.split(','):
        print '  - name:', property.lstrip('-')
        if property.startswith('-'):
            print '    direction: desc'

print """
# AUTOGENERATED

# This index.yaml is automatically updated whenever the dev_appserver
# detects that a new type of query is run.  If you want to manage the
# index.yaml file manually, remove the above marker line (the line
# saying "# AUTOGENERATED").  If you want to manage some indexes
# manually, move them above the marker line.  The index.yaml file is
# automatically uploaded to the admin console when you next deploy
# your application using appcfg.py."""
