#!/usr/bin/env python

INDEXES = """
django_admin_log:content_type,object_id,action_time
django_admin_log:user,-action_time
__Stat_Kind__:kind_name,-timestamp
prefixes_prefix:length,timestamp
domains_domain:com,-timestamp
""".split()

for length in range(1, 7):
    for property in 'length -english -spanish -french -german'.split():
        INDEXES.append('domains_domain:left%d,%s' % (length, property))
        INDEXES.append('domains_domain:right%d,%s' % (length, property))

for length in range(3, 7):
    INDEXES.append('domains_domain:left%d,com' % length)
    INDEXES.append('domains_domain:right%d,com' % length)

print 'indexes:'
for index in INDEXES:
    kind, properties = index.split(':')
    print
    print '- kind:', kind
    print '  properties:'
    for property in properties.split(','):
        print '  - name:', property.lstrip('-')
        if property.startswith('-'):
            print '    direction: desc'

print
print '# AUTOGENERATED'
